spring:
  redis:
    url: redis://:123456@localhost:6379/0
  datasource:
    url: jdbc:mysql://localhost:3306/databaseName?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
    username: root
    password: 123456

debug: true
